version: "3.9"

services:
  ssh-cuong-nguyen:
    build:
      context: .
      args:
        USERNAME: cuong.nguyen
        PASSWORD: cuongnguyen
    container_name: ssh-cuong-nguyen
    ports:
      - "2222:22"

  ssh-cuong-nm4:
    build:
      context: .
      args:
        USERNAME: cuong.nm4
        PASSWORD: cuongnm4
    container_name: ssh-cuong-nm4
    ports:
      - "2223:22"

  ssh-doan-ng:
    build:
      context: .
      args:
        USERNAME: doan.ng
        PASSWORD: doanng
    container_name: ssh-doan-ng
    ports:
      - "2224:22"

  ssh-duc-cuong:
    build:
      context: .
      args:
        USERNAME: duc.cuong
        PASSWORD: duccuong
    container_name: ssh-duc-cuong
    ports:
      - "2225:22"

  ssh-giang-ngo:
    build:
      context: .
      args:
        USERNAME: giang.ngo
        PASSWORD: giangngo
    container_name: ssh-giang-ngo
    ports:
      - "2226:22"

  ssh-haphong-ng:
    build:
      context: .
      args:
        USERNAME: haphong.ng
        PASSWORD: haphongng
    container_name: ssh-haphong-ng
    ports:
      - "2227:22"

  ssh-khanh-pd:
    build:
      context: .
      args:
        USERNAME: khanh.pd
        PASSWORD: khanhpd
    container_name: ssh-khanh-pd
    ports:
      - "2228:22"

  ssh-manhdung-ng:
    build:
      context: .
      args:
        USERNAME: manhdung.ng
        PASSWORD: manhdungng
    container_name: ssh-manhdung-ng
    ports:
      - "2229:22"

  ssh-minhhoa-tr:
    build:
      context: .
      args:
        USERNAME: minhhoa.tr
        PASSWORD: minhhoatr
    container_name: ssh-minhhoa-tr
    ports:
      - "2230:22"

  ssh-oanh-tt:
    build:
      context: .
      args:
        USERNAME: oanh.tt
        PASSWORD: oanhtt
    container_name: ssh-oanh-tt
    ports:
      - "2231:22"

  ssh-tien-oanh:
    build:
      context: .
      args:
        USERNAME: tien.oanh
        PASSWORD: tienoanh
    container_name: ssh-tien-oanh
    ports:
      - "2232:22"

  ssh-vancanh-ng:
    build:
      context: .
      args:
        USERNAME: vancanh.ng
        PASSWORD: vancanhng
    container_name: ssh-vancanh-ng
    ports:
      - "2233:22"

  ssh-vu-pd:
    build:
      context: .
      args:
        USERNAME: vu.pd
        PASSWORD: vupd
    container_name: ssh-vu-pd
    ports:
      - "2234:22"

  ssh-vuong-chinh:
    build:
      context: .
      args:
        USERNAME: vuong.chinh
        PASSWORD: vuongchinh
    container_name: ssh-vuong-chinh
    ports:
      - "2235:22"

  ssh-yen-pt1:
    build:
      context: .
      args:
        USERNAME: yen.pt1
        PASSWORD: yenpt1
    container_name: ssh-yen-pt1
    ports:
      - "2236:22"
